### PR TITLE
mild style tweaks to burning bridges (tiles are now black)

### PR DESCRIPTION
**Pull request by jeremyschoenherr**
sorry for the last minute PR! i felt the palette on the tiles was unnecessary and distracting from the fire. 
bridges-burning-alt5

### CODE REVIEW

**Comment by camilleroux** [comment]
No problem :)

**Comment by jeremyschoenherr** [comment]
🙏 🙏

**Comment by jeremyschoenherr** [comment]
p.s. if you select this to be included in the drop, it may need to use the gpu enabled preview rendering instances when you mint the project. the regular ones seem to have a problem with the OVERLAY blendMode. they don't look bad per se, but they a just a little different. thank you!

**Comment by camilleroux** [comment]
Ho thanks for the info!

**Pull request merged**
